# -*- coding: utf-8 -*-
"""flammm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUOofpGTLX39X0KX74Q0TgyoH9BSl4t0
"""

import numpy as np
import pandas as pd
from scipy.optimize import differential_evolution, minimize
from scipy.spatial import cKDTree



DATA_FILE = "/content/xy_data (1).csv"

df = pd.read_csv(DATA_FILE)
x, y = df["x"].values, df["y"].values
print(df.shape)
df.head()

T_MIN, T_MAX = 6.0, 60.0
THETA_BOUNDS = (0.0, np.deg2rad(50.0))
M_BOUNDS = (-0.05, 0.05)
X_BOUNDS = (0.0, 100.0)
SIN_EPS = 0.05

def recover_t_B(theta, X):
    xc, yc = x - X, y - 42.0
    ct, st = np.cos(theta), np.sin(theta)
    t_rec = xc * ct + yc * st
    B_rec = -xc * st + yc * ct
    return t_rec, B_rec

def fit_M(theta, X):
    t_rec, B_rec = recover_t_B(theta, X)
    s = np.sin(0.3 * t_rec)
    valid = (t_rec > T_MIN - 1) & (t_rec < T_MAX + 1) & (np.abs(s) > SIN_EPS)
    if valid.sum() < 10:
        return None, t_rec, B_rec
    ratio = B_rec[valid] / s[valid]
    pos = ratio > 1e-6
    if pos.sum() < 10:
        return None, t_rec, B_rec
    tt = t_rec[valid][pos]
    ln_ratio = np.log(ratio[pos])
    M_est = np.sum(tt * ln_ratio) / np.sum(tt * tt)   # LS slope through origin
    return M_est, t_rec, B_rec

def loss(params):
    theta, X = params
    M_est, t_rec, B_rec = fit_M(theta, X)
    if M_est is None or not (M_BOUNDS[0] <= M_est <= M_BOUNDS[1]):
        return 1e6
    pred_B = np.exp(M_est * np.abs(t_rec)) * np.sin(0.3 * t_rec)
    l1_B = np.mean(np.abs(pred_B - B_rec))
    out_of_range = np.mean(np.clip(T_MIN - t_rec, 0, None) + np.clip(t_rec - T_MAX, 0, None))
    return l1_B + 50.0 * out_of_range

# global search
result = differential_evolution(
    loss, [THETA_BOUNDS, X_BOUNDS],
    seed=42, tol=1e-14, maxiter=500, popsize=40,
    mutation=(0.3, 1.7), recombination=0.9, polish=True,
)
# local polish
local = minimize(loss, result.x, method="Nelder-Mead",
                  options={"xatol": 1e-12, "fatol": 1e-14, "maxiter": 20000, "maxfev": 20000})

theta_opt, X_opt = local.x
M_opt, t_rec, B_rec = fit_M(theta_opt, X_opt)

print("theta =", np.degrees(theta_opt), "deg  (", theta_opt, "rad)")
print("M     =", M_opt)
print("X     =", X_opt)
print("recovered t range:", t_rec.min(), "-", t_rec.max(), " (should be within 6..60)")

t_uniform = np.linspace(T_MIN, T_MAX, 5000)
ex = np.exp(M_opt * np.abs(t_uniform))
x_pred = t_uniform*np.cos(theta_opt) - ex*np.sin(0.3*t_uniform)*np.sin(theta_opt) + X_opt
y_pred = 42 + t_uniform*np.sin(theta_opt) + ex*np.sin(0.3*t_uniform)*np.cos(theta_opt)

tree = cKDTree(np.column_stack([x_pred, y_pred]))
dist_L1, _ = tree.query(np.column_stack([x, y]), p=1)
print("Mean L1 distance (data -> predicted curve):", dist_L1.mean())
print("Max  L1 distance (data -> predicted curve):", dist_L1.max())

import matplotlib.pyplot as plt
plt.figure(figsize=(7,5))
plt.scatter(x, y, s=8, alpha=0.4, label="data")
plt.plot(x_pred, y_pred, color="red", lw=1.5, label="fitted curve")
plt.legend(); plt.axis("equal"); plt.title("Fit check"); plt.show()











